# Generated by Django 3.0.7 on 2020-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jwtapi', '0002_auto_20200824_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bots',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='entity',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='intents',
            name='uuid',
            field=models.CharField(blank=True, default='0000000', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='uuid',
            field=models.CharField(default='NULL', max_length=64, unique=True),
        ),
    ]
