# Generated by Django 3.0.7 on 2020-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jwtapi', '0006_auto_20200908_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intents',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intents',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
